# Generated by Django 5.2.4 on 2026-06-17 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_jornal_arquivo_likes_edicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JornalComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Comentado em')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.jornalpost', verbose_name='Postagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornal_comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Comentário do Jornal',
                'verbose_name_plural': 'Comentários do Jornal',
                'ordering': ['criado_em'],
            },
        ),
    ]
