# Generated by Django 5.2.4 on 2026-06-17 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copiar_likes_para_reacoes(apps, schema_editor):
    """Converte cada curtida (👍) existente em uma reação equivalente,
    preservando a data original."""
    JornalLike = apps.get_model('core', 'JornalLike')
    JornalReacao = apps.get_model('core', 'JornalReacao')
    for like in JornalLike.objects.all():
        reacao = JornalReacao.objects.create(
            post_id=like.post_id,
            user_id=like.user_id,
            emoji='👍',
        )
        # criado_em tem auto_now_add; .update() ignora isso e preserva a data.
        JornalReacao.objects.filter(pk=reacao.pk).update(criado_em=like.criado_em)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_jornalcomentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JornalReacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=8, verbose_name='Reação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='core.jornalcomentario', verbose_name='Comentário')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='core.jornalpost', verbose_name='Postagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornal_reacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Reação do Jornal',
                'verbose_name_plural': 'Reações do Jornal',
            },
        ),
        migrations.RunPython(copiar_likes_para_reacoes, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='JornalLike',
        ),
        migrations.AddConstraint(
            model_name='jornalreacao',
            constraint=models.UniqueConstraint(fields=('post', 'user', 'emoji'), name='uniq_reacao_post'),
        ),
        migrations.AddConstraint(
            model_name='jornalreacao',
            constraint=models.UniqueConstraint(fields=('comentario', 'user', 'emoji'), name='uniq_reacao_comentario'),
        ),
    ]
