# Generated by Django 5.2.4 on 2026-06-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jornalreacao_delete_jornallike_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha_reabertura', models.CharField(blank=True, help_text="Não editar aqui — defina pela caixa 'Nova senha' no formulário.", max_length=255, verbose_name='Senha de reabertura (hash)')),
                ('prazo_validacao_dias', models.PositiveIntegerField(default=2, help_text='Dias para validar um card EXECUTADO antes de finalizar automaticamente.', verbose_name='Prazo de validação (dias)')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Segurança',
                'verbose_name_plural': 'Configuração de Segurança',
            },
        ),
    ]
