# Generated by Django 5.2.4 on 2026-06-23 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_configuracaoseguranca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioLiberacaoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_liberado', models.CharField(choices=[('nibo', 'Nibo Panel'), ('gestao', 'Gestão'), ('operacao', 'Operação'), ('zapmsg', 'ZapMsg (WhatsApp)'), ('painel_operacao', 'Painel Operação'), ('chat', 'Chat Interno'), ('financeiro', 'Financeiro')], max_length=30, verbose_name='Módulo liberado')),
                ('motivo', models.CharField(blank=True, help_text='Registro interno — não exibido ao usuário.', max_length=255, verbose_name='Motivo (opcional)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liberacoes_modulo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Liberação de módulo por usuário',
                'verbose_name_plural': 'Liberações de módulo por usuário',
                'ordering': ['user__username', 'modulo_liberado'],
                'unique_together': {('user', 'modulo_liberado')},
            },
        ),
    ]
