# Generated by Django 5.2.4 on 2026-07-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_criar_cargos_novos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioliberacaomodulo',
            name='modulo_liberado',
            field=models.CharField(choices=[('nibo', 'Nibo Panel'), ('gestao', 'Gestão'), ('operacao', 'Operação'), ('zapmsg', 'ZapMsg (WhatsApp)'), ('painel_operacao', 'Painel Operação'), ('chat', 'Chat Interno'), ('financeiro', 'Financeiro'), ('planilha', 'Planilha')], max_length=30, verbose_name='Módulo liberado'),
        ),
        migrations.AlterField(
            model_name='usuariorestricaomodulo',
            name='modulo_bloqueado',
            field=models.CharField(choices=[('nibo', 'Nibo Panel'), ('gestao', 'Gestão'), ('operacao', 'Operação'), ('zapmsg', 'ZapMsg (WhatsApp)'), ('painel_operacao', 'Painel Operação'), ('chat', 'Chat Interno'), ('financeiro', 'Financeiro'), ('planilha', 'Planilha')], max_length=30, verbose_name='Módulo bloqueado'),
        ),
    ]
