# Generated by Django 5.2.4 on 2026-04-17 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperadorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_original', models.CharField(max_length=255, unique=True, verbose_name='Login original')),
                ('nome_exibicao', models.CharField(max_length=255, verbose_name='Nome correto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Alias de Operador',
                'verbose_name_plural': 'Aliases de Operadores',
                'ordering': ['nome_exibicao'],
            },
        ),
        migrations.CreateModel(
            name='PainelConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_diaria_geral', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Meta diária geral')),
                ('intervalo_horas_sync', models.PositiveIntegerField(default=3, verbose_name='Intervalo sync (horas)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ultima_atualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última atualização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Painel',
                'verbose_name_plural': 'Configurações do Painel',
            },
        ),
        migrations.CreateModel(
            name='PainelSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('sucesso', models.BooleanField(default=False, verbose_name='Sucesso')),
                ('total_registros', models.PositiveIntegerField(default=0, verbose_name='Total de registros')),
                ('mensagem', models.TextField(blank=True, default='', verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Log de Sincronização',
                'verbose_name_plural': 'Logs de Sincronização',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorPainel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('meta_diaria', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Meta diária')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Supervisor do Painel',
                'verbose_name_plural': 'Supervisores do Painel',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PainelOperacaoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(blank=True, null=True, verbose_name='Data de referência')),
                ('data_acordo', models.DateTimeField(blank=True, null=True, verbose_name='Data do acordo')),
                ('data_emissao', models.DateTimeField(blank=True, null=True, verbose_name='Data da emissão')),
                ('data_etl_alteracao', models.DateTimeField(blank=True, null=True, verbose_name='Data ETL alteração')),
                ('numero_acordo', models.CharField(blank=True, default='', max_length=100, verbose_name='Número do acordo')),
                ('aco_id', models.BigIntegerField(db_index=True, verbose_name='Aco ID')),
                ('contrato', models.CharField(blank=True, default='', max_length=100, verbose_name='Contrato')),
                ('cliente', models.CharField(blank=True, default='', max_length=255, verbose_name='Cliente')),
                ('cpf_cnpj', models.CharField(blank=True, default='', max_length=30, verbose_name='CPF/CNPJ')),
                ('cre_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Credor ID')),
                ('credor', models.CharField(blank=True, default='', max_length=255, verbose_name='Credor')),
                ('filial', models.CharField(blank=True, default='', max_length=255, verbose_name='Filial')),
                ('tipo_contrato', models.CharField(blank=True, default='', max_length=255, verbose_name='Tipo contrato')),
                ('tipo_negociacao', models.CharField(blank=True, default='', max_length=255, verbose_name='Tipo negociação')),
                ('principal_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('desconto_principal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('principal_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('multa_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('desconto_multa', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('multa_liquida', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('juros_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('desconto_juros', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('juros_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('honorario_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('desconto_honorario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('honorario_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('despesas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('desconto_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('qtd_parcelas_acordo', models.IntegerField(default=0)),
                ('status_acordo', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_acordo', models.CharField(blank=True, default='', max_length=255)),
                ('emitido_por_login', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Emitido por login')),
                ('emitido_por_nome', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Emitido por nome')),
                ('supervisor_nome', models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='Supervisor')),
                ('valor_emissao', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Emissao')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Pago')),
                ('valor_avencer', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Avencer')),
                ('valor_quebra', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Quebra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro do Painel Operação',
                'verbose_name_plural': 'Registros do Painel Operação',
                'ordering': ['-data_emissao', '-aco_id'],
                'indexes': [models.Index(fields=['data_emissao'], name='painel_oper_data_em_dec645_idx'), models.Index(fields=['credor'], name='painel_oper_credor_ea9779_idx'), models.Index(fields=['supervisor_nome'], name='painel_oper_supervi_b199fb_idx'), models.Index(fields=['emitido_por_nome'], name='painel_oper_emitido_213113_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarteiraSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cre_id', models.IntegerField(unique=True, verbose_name='ID do Credor')),
                ('credor_nome', models.CharField(max_length=255, verbose_name='Nome do Credor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteiras', to='painel_operacao.supervisorpainel')),
            ],
            options={
                'verbose_name': 'Carteira por Supervisor',
                'verbose_name_plural': 'Carteiras por Supervisor',
                'ordering': ['credor_nome'],
            },
        ),
    ]
