# Generated by Django 5.2.4 on 2026-04-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel_operacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painelconfiguracao',
            name='meta_mensal_geral',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Meta mensal geral'),
        ),
        migrations.AlterField(
            model_name='carteirasupervisor',
            name='cre_id',
            field=models.BigIntegerField(unique=True, verbose_name='ID do Credor'),
        ),
        migrations.AlterField(
            model_name='painelconfiguracao',
            name='meta_diaria_geral',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Meta diária geral'),
        ),
        migrations.AlterField(
            model_name='paineloperacaoregistro',
            name='cre_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Credor ID'),
        ),
        migrations.AlterField(
            model_name='paineloperacaoregistro',
            name='tipo_negociacao',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Tipo negociação'),
        ),
    ]
