# Generated by Django 5.2.4 on 2026-04-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel_operacao', '0002_painelconfiguracao_meta_mensal_geral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainelOperacaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgo_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Pagamento ID')),
                ('aco_id', models.BigIntegerField(db_index=True, verbose_name='Acordo ID')),
                ('pct_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='PCT ID')),
                ('pgo_data', models.DateTimeField(blank=True, null=True, verbose_name='Data pagamento')),
                ('pgo_valor', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor pagamento')),
                ('fpg_id', models.IntegerField(blank=True, null=True, verbose_name='Forma pagamento ID')),
                ('pgo_parcial', models.BooleanField(default=False, verbose_name='Pagamento parcial')),
                ('pgo_etl_alteracao', models.DateTimeField(blank=True, null=True, verbose_name='ETL alteração')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pagamento do Painel Operação',
                'verbose_name_plural': 'Pagamentos do Painel Operação',
                'ordering': ['-pgo_data', '-pgo_id'],
            },
        ),
        migrations.AddField(
            model_name='paineloperacaoregistro',
            name='tem_pagamento',
            field=models.BooleanField(default=False, verbose_name='Tem pagamento'),
        ),
        migrations.AddIndex(
            model_name='paineloperacaoregistro',
            index=models.Index(fields=['aco_id'], name='painel_oper_aco_id_e43925_idx'),
        ),
        migrations.AddIndex(
            model_name='paineloperacaopagamento',
            index=models.Index(fields=['aco_id'], name='painel_oper_aco_id_d13ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='paineloperacaopagamento',
            index=models.Index(fields=['pgo_data'], name='painel_oper_pgo_dat_c3295e_idx'),
        ),
    ]
