# Generated by Django 5.2.4 on 2026-04-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel_operacao', '0003_paineloperacaopagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painelsynclog',
            name='tipo_sync',
            field=models.CharField(default='PAINEL', max_length=30, verbose_name='Tipo sync'),
        ),
        migrations.CreateModel(
            name='PainelOperacaoRelatorioGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_registro', models.CharField(db_index=True, max_length=30, verbose_name='Origem')),
                ('data_referencia', models.DateField(blank=True, null=True, verbose_name='Data de referência')),
                ('data_acordo', models.DateTimeField(blank=True, null=True, verbose_name='Data do acordo')),
                ('data_emissao', models.DateTimeField(blank=True, null=True, verbose_name='Data da emissão')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('data_etl_alteracao', models.DateTimeField(blank=True, null=True, verbose_name='Data ETL alteração')),
                ('numero_acordo', models.CharField(blank=True, default='', max_length=100, verbose_name='Número do acordo')),
                ('aco_id', models.BigIntegerField(db_index=True, verbose_name='Aco ID')),
                ('contrato', models.CharField(blank=True, default='', max_length=100, verbose_name='Contrato')),
                ('cliente', models.CharField(blank=True, default='', max_length=255, verbose_name='Cliente')),
                ('cpf_cnpj', models.CharField(blank=True, default='', max_length=30, verbose_name='CPF/CNPJ')),
                ('cre_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Credor ID')),
                ('credor', models.CharField(blank=True, default='', max_length=255, verbose_name='Credor')),
                ('filial', models.CharField(blank=True, default='', max_length=255, verbose_name='Filial')),
                ('tipo_contrato', models.CharField(blank=True, default='', max_length=255, verbose_name='Tipo contrato')),
                ('tipo_negociacao', models.CharField(blank=True, default='', max_length=500, verbose_name='Tipo negociação')),
                ('honorario_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('desconto_honorario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('honorario_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('qtd_parcelas_acordo', models.IntegerField(default=0)),
                ('status_acordo', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_acordo', models.CharField(blank=True, default='', max_length=255)),
                ('emitido_por_login', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Emitido por login')),
                ('emitido_por_nome', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Emitido por nome')),
                ('supervisor_nome', models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='Supervisor')),
                ('valor_emissao', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Emissao')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Pago')),
                ('valor_avencer', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Avencer')),
                ('valor_quebra', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Quebra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Relatório Geral do Painel',
                'verbose_name_plural': 'Relatórios Gerais do Painel',
                'ordering': ['-data_referencia', '-data_pagamento', '-data_emissao', '-aco_id'],
                'indexes': [models.Index(fields=['origem_registro'], name='painel_oper_origem__d14033_idx'), models.Index(fields=['data_referencia'], name='painel_oper_data_re_a23c2a_idx'), models.Index(fields=['data_pagamento'], name='painel_oper_data_pa_4e4363_idx'), models.Index(fields=['data_emissao'], name='painel_oper_data_em_a7ba94_idx'), models.Index(fields=['aco_id'], name='painel_oper_aco_id_55de36_idx'), models.Index(fields=['emitido_por_nome'], name='painel_oper_emitido_43e39b_idx')],
            },
        ),
    ]
