# Generated by Django 5.2.4 on 2026-05-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel_operacao', '0004_relatorio_exportacao_contrato_despesa'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='metaoperadorcarteira',
            new_name='painel_oper_ano_b14946_idx',
            old_name='painel_oper_ano_mes_93203f_idx',
        ),
        migrations.RenameIndex(
            model_name='metaoperadorcarteira',
            new_name='painel_oper_operado_55f5d9_idx',
            old_name='painel_oper_operado_0c8d41_idx',
        ),
        migrations.RenameIndex(
            model_name='metaoperadorcarteira',
            new_name='painel_oper_operado_e230f8_idx',
            old_name='painel_oper_operado_bcd862_idx',
        ),
        migrations.AddField(
            model_name='paineloperacaorelatoriogeral',
            name='observacao_contrato',
            field=models.TextField(blank=True, null=True),
        ),
    ]
