# Generated by Django 5.2.4 on 2026-05-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel_operacao', '0005_rename_painel_oper_ano_mes_93203f_idx_painel_oper_ano_b14946_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paineloperacaoregistro',
            name='observacao_contrato',
            field=models.TextField(blank=True, null=True, verbose_name='Observação do contrato'),
        ),
    ]
