# Generated by Django 5.2.4 on 2026-08-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel_operacao', '0011_painelconfiguracao_sync_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paineloperacaorelatoriogeral',
            name='valor_recuperado_parcelamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor Recuperado Parcelamento'),
        ),
        migrations.AddField(
            model_name='paineloperacaorelatoriogeral',
            name='valor_recuperado_refinanciamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor Recuperado Refinanciamento'),
        ),
    ]
