# Generated by Django 5.2.4 on 2026-02-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StakeholderMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(max_length=20)),
                ('kind', models.CharField(choices=[('customer', 'customer'), ('supplier', 'supplier')], max_length=20)),
                ('nibo_id', models.UUIDField()),
                ('name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nibo_stakeholder_map',
                'constraints': [models.UniqueConstraint(fields=('doc', 'kind'), name='uniq_nibo_stakeholder_map_doc_kind')],
            },
        ),
    ]
