"""
Django settings for backoffice project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys,os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_e!t1+41p^ii4+i=d3-sd=v@)=3927q9g7h%&27^re4e8b2t(z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Origens confiáveis para CSRF quando o HUB é servido via HTTPS (certificado mkcert).
# Necessário no Django 4+ para aceitar POSTs vindos destas URLs https.
CSRF_TRUSTED_ORIGINS = [
    'https://hub.credcom.local:8000',
    'https://192.168.0.204:8000',
    'https://localhost:8000',
    'https://127.0.0.1:8000',
]

# Versão exibida na navbar (Credcom Hub). Alterar aqui em cada release.
SITE_VERSION = "0.1.10"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',  # habilita runserver_plus (HTTPS no dev server)
    "nibo_panel",
    "widget_tweaks",
    "Gestao",
    "operacao",
    "core",
    "chat_interno",
    'zapmsg',
    "painel_operacao",
    "financeiro",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "core.middleware.ModuleGroupAccessMiddleware",
]

ROOT_URLCONF = 'backoffice.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # NOVO:
                "core.context_processors.nav_permissoes",
                "core.context_processors.minhas_notas",
                "core.context_processors.jornal_ctx",
                "core.context_processors.versao_site",
                "chat_interno.context_processors.chat_nav",
            ],
        },
    },
]

WSGI_APPLICATION = 'backoffice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "Backoffice",
        "USER": "postgres",
        "PASSWORD": "@Project123#",
        "HOST": "localhost",
        "PORT": "5432",
    },
    "cliente_db": {
        "ENGINE": "mssql",
        "NAME": "credcom",
        "USER": "credcom",
        "PASSWORD": "wUTZZpWnjlxfxidDe8Av",
        "HOST": "cobmais-stage.database.windows.net",
        "PORT": "1433",
        "OPTIONS": {
            "driver": "ODBC Driver 18 for SQL Server",
            "extra_params": "Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;",
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

NIBO_BASE_URL = "https://api.nibo.com.br/empresas/v1"
NIBO_API_TOKEN = os.getenv("NIBO_API_TOKEN")
NIBO_ACCOUNT_ID = os.getenv("NIBO_ACCOUNT_ID")

# Senha exigida para reenviar lançamentos que já estão marcados como enviado=True.
# Conhecida apenas pelo chefe do financeiro.
NIBO_REENVIO_SENHA = os.getenv("NIBO_REENVIO_SENHA")



LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/ambiente/"
LOGOUT_REDIRECT_URL = "/accounts/login/"



MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# sessão expira ao fechar navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 30 minutos sem atividade = perde sessão
SESSION_COOKIE_AGE = 1800

# renova a sessão a cada request
SESSION_SAVE_EVERY_REQUEST = True

ZAPMSG_CONNECTOR_URL = os.getenv("ZAPMSG_CONNECTOR_URL", "http://127.0.0.1:3010")
ZAPMSG_WEBHOOK_TOKEN = os.getenv("ZAPMSG_WEBHOOK_TOKEN", "dsr_zapmsg_2026")

# Mídia do ZapMsg trafega em base64 (webhook de entrada e upload de saída).
# O padrão do Django (2.5MB) corta arquivos maiores silenciosamente, então
# alinhamos com o limite de 80MB do connector.
DATA_UPLOAD_MAX_MEMORY_SIZE = 80 * 1024 * 1024  # 80 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 80 * 1024 * 1024  # 80 MB

# Envio automático de remessa ao Nibo (dia útil anterior).
# Desligado por padrão: ligue só depois de validar com --dry-run no servidor.
NIBO_AUTO_ENVIO_ATIVO = os.getenv("NIBO_AUTO_ENVIO_ATIVO", "0") == "1"
NIBO_AUTO_ENVIO_HORA = int(os.getenv("NIBO_AUTO_ENVIO_HORA", "9"))  # hora (0-23)

