# Generated by Django 5.2.4 on 2026-03-20 18:22

import django.db.models.deletion
import django.utils.timezone
import zapmsg.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZapConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=zapmsg.models.generate_session_id, max_length=120, unique=True)),
                ('status', models.CharField(choices=[('desconectado', 'Desconectado'), ('conectando', 'Conectando'), ('aguardando_qr', 'Aguardando QR'), ('conectado', 'Conectado'), ('erro', 'Erro')], default='desconectado', max_length=20)),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('nome_perfil', models.CharField(blank=True, default='', max_length=120)),
                ('qr_code', models.TextField(blank=True, default='')),
                ('ultimo_erro', models.TextField(blank=True, default='')),
                ('conectado_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_ping', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zap_conta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZapContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(max_length=120)),
                ('numero', models.CharField(blank=True, default='', max_length=30)),
                ('nome', models.CharField(blank=True, default='', max_length=120)),
                ('nome_exibicao', models.CharField(blank=True, default='', max_length=120)),
                ('ultima_interacao_em', models.DateTimeField(blank=True, null=True)),
                ('arquivado', models.BooleanField(default=False)),
                ('bloqueado', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='zapmsg.zapconta')),
            ],
            options={
                'ordering': ['-ultima_interacao_em', '-id'],
                'unique_together': {('conta', 'wa_id')},
            },
        ),
        migrations.CreateModel(
            name='ZapConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_mensagem', models.TextField(blank=True, default='')),
                ('ultima_mensagem_em', models.DateTimeField(blank=True, null=True)),
                ('nao_lidas', models.PositiveIntegerField(default=0)),
                ('fixada', models.BooleanField(default=False)),
                ('arquivada', models.BooleanField(default=False)),
                ('status_atendimento', models.CharField(blank=True, default='', max_length=30)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='zapmsg.zapconta')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='zapmsg.zapcontato')),
            ],
            options={
                'ordering': ['-fixada', '-ultima_mensagem_em', '-id'],
                'unique_together': {('conta', 'contato')},
            },
        ),
        migrations.CreateModel(
            name='ZapMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externo_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('direction', models.CharField(choices=[('in', 'Recebida'), ('out', 'Enviada')], max_length=10)),
                ('tipo', models.CharField(choices=[('texto', 'Texto')], default='texto', max_length=20)),
                ('status_envio', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('entregue', 'Entregue'), ('lida', 'Lida'), ('recebida', 'Recebida'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('texto', models.TextField(blank=True, default='')),
                ('media_url', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('enviada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='zapmsg.zapconversa')),
            ],
            options={
                'ordering': ['enviada_em', 'id'],
            },
        ),
    ]
