# Generated by Django 5.2.4 on 2026-03-27 17:46

import zapmsg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapmsg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapmensagem',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=zapmsg.models.zap_media_upload_to),
        ),
        migrations.AddField(
            model_name='zapmensagem',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='zapmensagem',
            name='nome_arquivo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='zapmensagem',
            name='tamanho_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zapmensagem',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('audio', 'Áudio'), ('documento', 'Documento'), ('video', 'Vídeo')], default='texto', max_length=20),
        ),
    ]
