# Generated by Django 5.2.4 on 2026-03-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapmsg', '0002_zapmensagem_arquivo_zapmensagem_mime_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapmensagem',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='zapmensagem',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='zapmensagem',
            name='nome_arquivo',
        ),
        migrations.RemoveField(
            model_name='zapmensagem',
            name='tamanho_bytes',
        ),
        migrations.AlterField(
            model_name='zapmensagem',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('audio', 'Áudio'), ('imagem', 'Imagem'), ('documento', 'Documento'), ('video', 'Vídeo'), ('arquivo', 'Arquivo')], default='texto', max_length=20),
        ),
    ]
