# Generated by Django 5.2.4 on 2026-02-24 13:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexo',
            options={'ordering': ['-enviado_em'], 'verbose_name': 'Anexo (Operação)', 'verbose_name_plural': 'Anexos (Operação)'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Comentário (Operação)', 'verbose_name_plural': 'Comentários (Operação)'},
        ),
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['ordem', '-prazo', '-id'], 'verbose_name': 'Tarefa (Operação)', 'verbose_name_plural': 'Tarefas (Operação)'},
        ),
        migrations.AlterField(
            model_name='anexo',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacao_anexos_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='nome_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacao_comentarios_autor', to=settings.AUTH_USER_MODEL),
        ),

        # ✅ FIX AQUI: FK NÃO PODE TER default=timezone.now
        migrations.AlterField(
            model_name='tarefa',
            name='atribuida_para',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='operacao_tarefas_atribuidas',
                to=settings.AUTH_USER_MODEL
            ),
        ),

        migrations.AlterField(
            model_name='tarefa',
            name='criada_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prazo',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('ativa', models.BooleanField(default=True)),
                ('membros', models.ManyToManyField(blank=True, related_name='operacao_equipes', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacao_equipes_supervisionadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipe (Operação)',
                'verbose_name_plural': 'Equipes (Operação)',
            },
        ),
    ]