# Generated by Django 5.2.4 on 2026-04-01 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0003_tarefa_deleted_at_tarefa_deleted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacaoPermissaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_criar_chamado_supervisor', models.BooleanField(default=True, verbose_name='Pode criar chamado para o supervisor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operacao_permissao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Permissão de usuário (Operação)',
                'verbose_name_plural': 'Permissões de usuários (Operação)',
            },
        ),
    ]
