# Generated by Django 5.2.4 on 2026-05-12 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0004_operacaopermissaousuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='equipe',
            name='supervisores',
            field=models.ManyToManyField(blank=True, related_name='operacao_equipes_supervisionadas', to=settings.AUTH_USER_MODEL, verbose_name='Supervisores'),
        ),
    ]
