# Generated by Django 5.2.4 on 2026-06-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0007_comentario_eh_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='finalizado_automaticamente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='eh_devolucao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='codigo',
            field=models.CharField(blank=True, help_text='Identificador único do chamado (ex: OPE-00001). Gerado automaticamente.', max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='pendente_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('executando', 'Executando'), ('executado', 'Executado'), ('pendente', 'Pendente de validação'), ('feita', 'Finalizada')], default='aberta', max_length=12),
        ),
    ]
