# Generated by Django 5.2.4 on 2026-02-20 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('prazo', models.DateTimeField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('feita', 'Feita')], default='aberta', max_length=10)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prioridade', models.BooleanField(default=False)),
                ('atribuida_para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_atribuidas', to=settings.AUTH_USER_MODEL)),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
