# Generated by Django 5.2.4 on 2026-02-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0002_tarefaanexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefaanexo',
            name='nome_original',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
