# Generated by Django 5.2.4 on 2026-02-20 16:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0003_tarefaanexo_nome_original'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TarefaAnexo',
            new_name='Anexo',
        ),
    ]
