# Generated by Django 5.2.4 on 2026-02-23 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0005_tarefa_criada_em_tarefa_finalizado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AddField(
            model_name='tarefa',
            name='executado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_em_execucao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('executando', 'Executando'), ('executado', 'Executado'), ('feita', 'Feita')], default='aberta', max_length=12),
        ),
    ]
