# Generated by Django 5.2.4 on 2026-05-14 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_interno', 'chat_migration_0009_chatbloqueio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLiberacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo (opcional)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Liberação de chat entre usuários',
                'verbose_name_plural': 'Liberações de chat entre usuários',
                'ordering': ['user_a__username', 'user_b__username'],
            },
        ),
        migrations.AlterModelOptions(
            name='chatmonitorconfig',
            options={'verbose_name': 'Configuração de monitor', 'verbose_name_plural': 'Configurações de monitor'},
        ),
        migrations.AlterModelOptions(
            name='chatvinculooperador',
            options={'verbose_name': 'Vínculo operador-supervisor', 'verbose_name_plural': 'Vínculos operador-supervisor'},
        ),
        migrations.RemoveConstraint(
            model_name='chatvinculooperador',
            name='uniq_chat_vinculo_operador_supervisor',
        ),
        migrations.RenameField(
            model_name='chatmonitorconfig',
            old_name='can_monitor',
            new_name='monitorado',
        ),
        migrations.AddField(
            model_name='chatmonitorconfig',
            name='notificar_fone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatbloqueio',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo (opcional)'),
        ),
        migrations.AlterField(
            model_name='chatvinculooperador',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_como_operador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatvinculooperador',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_como_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chatvinculooperador',
            constraint=models.UniqueConstraint(fields=('operador', 'supervisor'), name='uniq_vinculo_operador_supervisor'),
        ),
        migrations.AddField(
            model_name='chatliberacao',
            name='user_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_liberacoes_como_a', to=settings.AUTH_USER_MODEL, verbose_name='Usuário A'),
        ),
        migrations.AddField(
            model_name='chatliberacao',
            name='user_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_liberacoes_como_b', to=settings.AUTH_USER_MODEL, verbose_name='Usuário B'),
        ),
        migrations.AddConstraint(
            model_name='chatliberacao',
            constraint=models.UniqueConstraint(fields=('user_a', 'user_b'), name='uniq_chat_liberacao_par'),
        ),
    ]
