# Generated by Django 5.2.4 on 2026-02-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_interno', '0002_chatpresence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatPresence',
        ),
    ]
