# Generated by Django 5.2.4 on 2026-02-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_interno', '0004_message_imagem_e_texto_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='chat_interno/imagens/'),
        ),
    ]
