# Generated by Django 5.2.4 on 2026-06-12 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_interno', '0011_chatliberacaogrupo_chatmonitorconfig_pode_enviar_massa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'id'], name='chat_msg_conv_id_idx'),
        ),
    ]
