# Generated by Django 5.2.4 on 2026-07-10 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanilhaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cre_id', models.BigIntegerField(db_index=True, verbose_name='Código (cre_id)')),
                ('carteira_nome', models.CharField(db_index=True, max_length=255, verbose_name='Carteira')),
                ('operador_nome', models.CharField(db_index=True, max_length=255, verbose_name='Operador')),
                ('nr_contrato', models.CharField(db_index=True, max_length=100, verbose_name='Nr Contrato')),
                ('tipo_contrato', models.CharField(blank=True, default='', max_length=255, verbose_name='Tipo do Contrato')),
                ('empreendimento', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Empreendimento')),
                ('atraso_real', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Atraso real (dias)')),
                ('vlr_total', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=14, verbose_name='Vlr total')),
                ('status_antigo', models.CharField(blank=True, default='', max_length=100, verbose_name='Status Antigo')),
                ('cpf_cnpj', models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='CPF/CNPJ')),
                ('nome_cliente', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Nome')),
                ('status_atual', models.CharField(blank=True, default='', max_length=100, verbose_name='Status Atual')),
                ('prioridade', models.BooleanField(db_index=True, default=False, verbose_name='Prioridade')),
                ('prioridade_em', models.DateTimeField(blank=True, null=True)),
                ('destaque_cor', models.CharField(blank=True, default='', max_length=20, verbose_name='Cor de destaque')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('prioridade_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planilha_prioridades', to=settings.AUTH_USER_MODEL, verbose_name='Prioridade marcada por')),
            ],
            options={
                'verbose_name': 'Contrato da Planilha',
                'verbose_name_plural': 'Contratos da Planilha',
                'ordering': ['-prioridade', '-atraso_real', 'nome_cliente'],
            },
        ),
        migrations.CreateModel(
            name='PlanilhaAcrescimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('telefone', 'Telefone'), ('email', 'E-mail'), ('nota', 'Nota / Lembrete')], max_length=20, verbose_name='Tipo')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planilha_acrescimos', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acrescimos', to='planilha.planilhacontrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Acréscimo ao Contrato',
                'verbose_name_plural': 'Acréscimos aos Contratos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PlanilhaImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cre_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Código (cre_id)')),
                ('carteira_nome', models.CharField(max_length=255, verbose_name='Carteira')),
                ('arquivo_nome', models.CharField(blank=True, default='', max_length=255, verbose_name='Arquivo importado')),
                ('total_contratos', models.PositiveIntegerField(default=0, verbose_name='Total de contratos')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planilha_importacoes', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
            ],
            options={
                'verbose_name': 'Importação de Planilha',
                'verbose_name_plural': 'Importações de Planilha',
                'ordering': ['carteira_nome'],
            },
        ),
        migrations.AddField(
            model_name='planilhacontrato',
            name='importacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='planilha.planilhaimportacao', verbose_name='Importação'),
        ),
        migrations.CreateModel(
            name='PlanilhaImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cre_id', models.BigIntegerField(db_index=True, verbose_name='Código (cre_id)')),
                ('carteira_nome', models.CharField(blank=True, default='', max_length=255, verbose_name='Carteira')),
                ('total_inseridos', models.PositiveIntegerField(default=0, verbose_name='Contratos inseridos')),
                ('total_removidos', models.PositiveIntegerField(default=0, verbose_name='Contratos removidos (base antiga)')),
                ('inconsistencias', models.PositiveIntegerField(default=0, verbose_name='Inconsistências')),
                ('importado_mesmo_com_erros', models.BooleanField(default=False)),
                ('arquivo_devolvido', models.CharField(blank=True, default='', max_length=255, verbose_name='Excel da base antiga devolvido')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planilha_import_logs', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
            ],
            options={
                'verbose_name': 'Log de Importação',
                'verbose_name_plural': 'Logs de Importação',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='planilhacontrato',
            index=models.Index(fields=['cre_id', 'operador_nome'], name='planilha_pl_cre_id_1571e1_idx'),
        ),
        migrations.AddIndex(
            model_name='planilhacontrato',
            index=models.Index(fields=['cre_id', 'cpf_cnpj'], name='planilha_pl_cre_id_d9403c_idx'),
        ),
    ]
