# Generated by Django 5.2.4 on 2026-07-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0002_grupo_backoffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilhacontrato',
            name='fila_ordem',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Ordem na fila'),
        ),
    ]
