# Generated by Django 5.2.4 on 2026-07-15 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0003_planilhacontrato_fila_ordem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanilhaStatusAcionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Status')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Status de Acionamento',
                'verbose_name_plural': 'Status de Acionamento',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanilhaAcionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, default='', verbose_name='Comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acionamentos', to='planilha.planilhacontrato', verbose_name='Contrato')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planilha_acionamentos', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acionamentos', to='planilha.planilhastatusacionamento', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Acionamento',
                'verbose_name_plural': 'Acionamentos (histórico)',
                'ordering': ['-criado_em'],
            },
        ),
    ]
