# Generated by Django 5.2.4 on 2026-07-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0005_seed_status_acionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilhacontrato',
            name='status_atual_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Status Atual'),
        ),
        migrations.AlterField(
            model_name='planilhacontrato',
            name='status_atual',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Status Atual'),
        ),
    ]
