# Generated by Django 5.2.4 on 2026-08-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0006_planilhacontrato_status_atual_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilhacontrato',
            name='cod_empresa',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cód. Empresa'),
        ),
        migrations.AddField(
            model_name='planilhacontrato',
            name='cod_obra',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cód. Obra'),
        ),
    ]
