# Generated by Django 5.2.4 on 2026-08-07 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0007_planilhacontrato_cod_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanilhaCompartilhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colegas', models.ManyToManyField(blank=True, related_name='planilha_compartilhado_com', to=settings.AUTH_USER_MODEL, verbose_name='Também pode ver a base de')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planilha_compartilhamentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário (ganha acesso extra)')),
            ],
            options={
                'verbose_name': 'Compartilhamento de Base (Planilha)',
                'verbose_name_plural': 'Compartilhamentos de Base (Planilha)',
            },
        ),
    ]
